name: virtual_keyboard
version: "1.0.0"
description: A customizable flutter widget that allow to show virtual keyboard and handle keyboard taps.
repository: "https://github.com/surfstudio/flutter-virtual-keyboard"
issue_tracker: "https://github.com/surfstudio/flutter-virtual-keyboard/issues"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  ink_widget: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0
  

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
